-- eMart schema

CREATE TABLE SystemRules (
    rule_name VARCHAR2(50) PRIMARY KEY,
    rule_value NUMBER(10, 2)
);

INSERT INTO SystemRules (rule_name, rule_value) VALUES ('GOLD_DISCOUNT_PERCENT', 10);
INSERT INTO SystemRules (rule_name, rule_value) VALUES ('SILVER_DISCOUNT_PERCENT', 5);
INSERT INTO SystemRules (rule_name, rule_value) VALUES ('NEW_DISCOUNT_PERCENT', 10);
INSERT INTO SystemRules (rule_name, rule_value) VALUES ('SHIPPING_FEE_PERCENT', 10);
INSERT INTO SystemRules (rule_name, rule_value) VALUES ('SHIPPING_WAIVE_THRESHOLD', 100);
INSERT INTO SystemRules (rule_name, rule_value) VALUES ('GOLD_STATUS_THRESHOLD', 500);
INSERT INTO SystemRules (rule_name, rule_value) VALUES ('SILVER_STATUS_THRESHOLD', 100);
COMMIT;


CREATE TABLE Products (
    stock_number VARCHAR2(50) PRIMARY KEY,
    manufacturer VARCHAR2(100),
    model_number VARCHAR2(100),
    category VARCHAR2(100),
    description CLOB,
    warranty_months NUMBER,
    price NUMBER(10, 2)
);


CREATE TABLE ProductCompatibility (
    stock_number VARCHAR2(50),
    compatible_stock_number VARCHAR2(50),
    PRIMARY KEY (stock_number, compatible_stock_number),
    FOREIGN KEY (stock_number) REFERENCES Products(stock_number),
    FOREIGN KEY (compatible_stock_number) REFERENCES Products(stock_number)
);


CREATE TABLE Customers (
    customer_id VARCHAR2(50) PRIMARY KEY,
    password VARCHAR2(100),
    name VARCHAR2(150),
    email VARCHAR2(100),
    address VARCHAR2(255),
    status VARCHAR2(20) -- Gold, Silver, Green, New
);


CREATE TABLE Orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR2(50),
    order_date DATE,
    total_amount NUMBER(10, 2),
    shipping_fee NUMBER(10, 2),
    discount_amount NUMBER(10, 2),
    is_deleted NUMBER(1) DEFAULT 0,
    FOREIGN KEY (customer_id) REFERENCES Customers(customer_id)
);


CREATE TABLE OrderItems (
    order_id NUMBER,
    stock_number VARCHAR2(50),
    quantity NUMBER,
    price NUMBER(10, 2), -- Price at the time of purchase
    PRIMARY KEY (order_id, stock_number),
    FOREIGN KEY (order_id) REFERENCES Orders(order_id),
    FOREIGN KEY (stock_number) REFERENCES Products(stock_number)
);

CREATE TABLE Managers (
    manager_id VARCHAR2(50) PRIMARY KEY,
    password VARCHAR2(100)
);

INSERT INTO Managers (manager_id, password) VALUES ('admin', 'admin');
COMMIT;
